# Localhost : http://localhost:4000/vue-directive-tooltip/

# Site settings
title: Vue Directive Tooltip
email:
description: > # this means to ignore newlines until "baseurl:"
  Tooltips made easy with popper.js
baseurl: "/vue-directive-tooltip" # the subpath of your site, e.g. /blog/
url: "https://hekigan.github.io" # the base hostname & protocol for your site
github_username:  hekigan

# Build settings
# highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# plugin
plugins:
  - jekyll-gist

lang: en